---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-deployment2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image:  52.141.39.195:5000/httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
  labels:
    app: apache
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
  type: LoadBalancer
