apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: docker.io/purecap/nginx-test:0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  namespace: default
  labels:
    app: nginx2
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
  type: LoadBalancer
